// constants/SUBSCRIPTION.ts

export const SUBSCRIPTION_CONFIG = {
  // 缓存前缀
  CACHE_PREFIX: 'subscription_status:',
  // 缓存过期时间（秒）：3天
  CACHE_TTL_SECONDS: 3 * 24 * 60 * 60,
};

export const SUBSCRIPTION_ERRORS = {
  FETCH_FAILED: 'SUBSCRIPTION_STATUS_FETCH_FAILED',
  SERVICE_UNAVAILABLE: 'SUBSCRIPTION_SERVICE_UNAVAILABLE',
  INVALID_TENANT: 'INVALID_TENANT_ID',
}; 