export const TENANT_UNIQUE_FIELDS = ['email', 'subdomain'] as const;
export const TENANT_STATUS = {
    ACTIVE: 'ACTIVE',
    DISABLED: 'DISABLED',
    DELETED: 'DELETED',
} as const;

export const TENANT_ERRORS = {
    EMAIL_EXISTS: 'EMAIL_ALREADY_REGISTERED',
    SUBDOMAIN_EXISTS: 'SUBDOMAIN_ALREADY_REGISTERED',
    TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
    INVALID_PASSWORD: 'INVALID_PASSWORD',
    NOT_ALLOWED: 'OPERATION_NOT_ALLOWED',
} as const;